var mongo = require('mongodb').MongoClient;

module.exports.getOptions = function(req, res){
    mongo.connect('mongodb://localhost:27017/aknApp', function(err, db) {
        if(err) {
            console.log("db connection error");
            throw err;
        }
        else{
            db.listCollections().toArray(function(error,response){
                if (error)
                    console.log(error);
                else{
                    res.send(response);
                }
            });
        }
        

    });
}

module.exports.registro = function(req, res){
    mongo.connect('mongodb://localhost:27017/aknApp', function(err, db) {
        if(err) {
            console.log("db connection error");
            throw err;
        }
        else{
            var Collection = db.collection(req.body.motivo)
            Collection.insert(req.body, function(error,docsInserted){
                if(docsInserted){
                    console.log("Database updated!");
                    console.log(docsInserted);
                    //send survivor's unique ID, generated by DB
                    res.send(docsInserted);
                }
            });
            db.close();
        }
    });
}
